title: byDragica.com
email: hello@bydragica.com
description: >
  Dragica is a Belgrade-born, Amsterdam-based digital creative, with a passion for photography and storytelling.
baseurl: ""
url: "https://bydragica.com"
markdown: kramdown
